apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-host-pvc
spec:
  volumeName: my-host-pv                          # which "PersistentVolume" we wanna use? we define here. We shouldnt claim with volumeName, we can also claim by resources. // it is Dynamic Volume Provisioning it is advance topic, we will go with static provisioning.
  storageClassName: standart                      # use same with the pv.yaml storageClassName
  accessModes:
    - ReadWriteOnce
  resources:                                      # which resources we want to get for this claim. counter part for pv.yaml capacity place.
    requests:
      storage: 1Gi

# we need to connect this persistent volume claim to the deployment.yaml !!