apiVersion: v1
kind: Service
metadata:
  name: crazy-harbor-eureka
  labels:
    group: crazy-harbor-group
spec:
  selector:
    app: crazy-harbor-eureka-pod
  ports:
    - protocol: 'TCP'
      port: 8761
      targetPort: 8761
  type: LoadBalancer