spring:
  application:
    name: APPLICATION.FORUM.forum-eureka-server


server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always