spring:
  application:
    name: crazy-harbor-eureka-server


server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

eureka:
  client:
    registerWithEureka: false # "false" -> it prevents the register itself to the eureka server.
    fetchRegistry: false # "false" -> it prevents reaching register documents of itself.


## debug: true # it shows autoconfigured beans in the console


