apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    group: crazy-harbor-group
spec:
  selector:
    matchLabels:
      app: redis-pod
      dummykey: dummyvalue
  replicas: 1
  # number of pod instances we wanted , defult is 1
  template:                 # pods that should be created as part of this deployment (--image)
    metadata:
      labels:
        app: redis-pod
        dummykey: dummyvalue
    spec:                 # we define how this POD should be configured
      hostname: redis
      containers:
        - name: redis
          image: redis
          # env:
          #   - name: MY_SPECIAL_ENV
          #     valueFrom:
          #       configMapKeyRef:
          #         name: my-data-store-env           # this name is specified in configMap object as other resource
          #         key: my_folder                    # this name is specified in configMap object as other resource
          #volumeMounts:
          #  - name: my-volume-pv
          #    mountPath: /app/story
          #livenessProbe:
          #  httpGet:
          #    path: /                                           # can be different(e.g /example - /health - /banana)
          #    port: 6379                                        # exposed container port
          #    httpHeaders:                                     # we can add headers too but no need.
          #  periodSeconds: 20                                   # control frequency -> 20 seconds in this case.
          #  initialDelaySeconds: 60                             # the time that k8 should checks the health for the first time. -> after the 60 second passed from the start, it checks the application.
        # imagePullPolicy: Always                               # this makes the pull the ":latest" tag image always. Also if you give that always you don't need to add tag end of the image name in the image definition above. (you can also set it to never)
      #volumes:
      #  - name: my-volume-pv
      #    persistentVolumeClaim:
      #      claimName: my-host-pvc                               # you can find the name in host-pvc .yaml

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    group: crazy-harbor-group
spec:
  selector:
    app: redis-pod
  ports:
    - protocol: 'TCP'
      port: 6379
      targetPort: 6379
  type: LoadBalancer

---
